version: "3.8"
services:
  edu-mysql:
    image: mysql:8.0.32
    container_name: edu-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password #mandatory
      - MYSQL_DATABASE=edu-mysql
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=password
    volumes:
      - ~/.docker-conf/mysql:/var/lib/mysql